server:
  port: 8080

spring:
  application:
    name: soap-service
  profiles:
    active: local

soap:
  security:
    users:
      admin: adminpass
      user: userpass

logging:
  level:
    pl.kathelan.soap.interceptor: DEBUG
